### PR TITLE
Add wayland and windows start options

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
This PR adds start options for Wayland and Windows.

This would solve issue #3582.

**To Do if this PR is merged:**

- [ ] Adjust [Windows section](https://docs.magicmirror.builders/getting-started/installation.html#windows) in documentation
- [ ] Add Wayland section to the documentation

### CODE REVIEW

**Comment by KristjanESPERANTO** [comment]
I dropped the attempt to add an windows installation option for this PR.

**Comment by sdetweil** [comment]
@KristjanESPERANTO if you used my shell js app it could be on install-mm

**Comment by KristjanESPERANTO** [comment]
> @KristjanESPERANTO if you used my shell js app it could be on install-mm

I think it's good to handle this in different PRs. This one handles the start options and a new one could handle the installation.

**Review by khassel — APPROVED** [review]

**Comment by khassel** [comment]
btw tested this in VirtualBox

```bash
"install-mm:windows": "cmd /c npm install --ignore-scripts --no-audit --no-fund --no-update-notifier --only=prod --omit=dev && echo 'Installing vendor files ...' && cd vendor && npm install --loglevel=error --no-audit --no-fund --no-update-notifier && echo 'Installing fonts ...' && cd fonts && npm install --loglevel=error --no-audit --no-fund --no-update-notifier",`
```

and beside a small error (should be `cd ../fonts`) it worked :)

**Comment by sdetweil** [comment]
i think this could have been done together

my postinstall using my launcher 
```json
"postinstall": "node js/es.js \"npm run install-vendor && npm run install-fonts && echo MagicMirror² installation finished successfully!\n\":npm run install-vendor & npm run install-fonts & echo MagicMirror² installation finished successfully!",
```
then we don't need multiple divergent commands..  (to document and support)

**Comment by sdetweil** [comment]
then we just use run mm-install
if you ran install postinstall would be the same

**Comment by sdetweil** [comment]
we can do the same on start too.. 

js/es.js linux_command : windows_command

**Comment by KristjanESPERANTO** [comment]
> we can do the same on start too..
> 
> js/es.js linux_command : windows_command

We would need something like this: `js/exec_script.js x11_command : wayland_command : windows_command`.

> less confusing for our users..

Yes, but different start options should not overwhelm a tinkerer. Also, when someone uses the additional commands, they should always be reminded that they are doing something that is not the default. This might help them to solve problems themselves and need less support.

Perhaps I will argue in a different direction in the future 😅. But I often have the thought that it might not be a good idea to make it too easy for our users (who are tinkerers). If we automate everything, they understand the system less and need more support. That's why I liked the decision that only the manual installation is the official one.

**Pull request merged**
