### PR TITLE
add address and ipWhitelist to all test configs

### PR DESCRIPTION
**Pull request by khassel**
All test configs have been updated to allow full external access, allowing for easier debugging (especially when running as a container)

### CODE REVIEW

**Comment by sdetweil** [comment]
just added 6 configs today, sorry

**Comment by khassel** [comment]
> just added 6 configs today, sorry

on your fork or here?

**Comment by sdetweil** [comment]
on my fork.  i'll fix it..

**Comment by sdetweil** [comment]
one other thing, relative to test..
I was trying to do individual tests, via npm start with MM_CONFIG_FILE=test/configs/....
but
the test  path isn't enabled unless JEST is running.. (so couldn't load the ics file) 
so had to define that env var (as something) to get the path 
was worried about other side effects

**Comment by khassel** [comment]
> the test path isn't enabled unless JEST is running.. (so couldn't load the ics file)

I added this with the last release and can revert it (with another PR) if you want. I didn't think of your use case

**Comment by sdetweil** [comment]
I can put it back with mine, just wanted to make sure there was no other intent

**Comment by khassel** [comment]
o.k., it was this change:

grafik

**Review by rejas — APPROVED** [review]

**Pull request merged**
