### PR TITLE
Correct apibase of weathergov weatherprovider to match documentation

### PR DESCRIPTION
**Pull request by rejas**
Fixes part of #2926

### CODE REVIEW

**Review by khassel — APPROVED** [review]

**Comment by khassel** [comment]
would merge it if you resolve conflicts ... (same for https://github.com/MichMich/MagicMirror/pull/2928)

**Comment by rejas** [comment]
Not Sure If its OK yet to merge, since i dont want to risk breaking changes...

**Comment by khassel** [comment]
looked ready, may better convert back to draft until really ready?

**Comment by rejas** [comment]
Made a draft, fixed conflict, will think about it later, now too late for this :-)

**Comment by rejas** [comment]
As for whats left to do: Think about these concerns: https://github.com/MichMich/MagicMirror/issues/2926#issuecomment-1265874067

**Comment by rejas** [comment]
Code now matches docs again

**Pull request merged**
