### PR TITLE
Improved, fixed and added translations for estonian

### PR DESCRIPTION
**Pull request by illimarkangur**
Improved wording, fixed grammatical errors and added new translations to the et.json file.

### CODE REVIEW

**Comment by rejas** [comment]
Thanks. Could you add a CAHNGELOG entry for your PR too?

**Comment by illimarkangur** [comment]
My branch seemed to be forked from the MagicMirrorOrg:master instead of MagicMirrorOrg:develop branch. All I added was:
`- Updated translations for estonian (#3371)`
to the ### Updated header on row 27.

**Comment by sdetweil** [comment]
you can 

git checkout develop

and the create a sub branch from there

**Comment by illimarkangur** [comment]
Doesn't that mean I have to make a new PR?

**Comment by rejas** [comment]
> Doesn't that mean I have to make a new PR?

Not necessarily, you can "rebase" your local branch unto develop and push that branch then (probably have to force it).

But if you dont feel experienced enough for this git stuff, then just make a new pr.

**Pull request merged**
