### PR TITLE
Show animations

### PR DESCRIPTION
**Pull request by sdetweil**
I am adding the animateIn/Out support to MMM-Config, but I need the list of animations..
but they are not visible in js/animateCSS.js (from require)

adding an export satisfies that

side issue, these would go in a dropdown list
what value can I use for the default behavior? none/default?
don't want an error produced..
should I add code to check for this value to prevent error?

### CODE REVIEW

**Comment by sdetweil** [comment]
no need to add code, if the entry is not found in list it is ignored..

**Review by rejas — APPROVED** [review]

**Comment by bugsounet** [comment]
image

**Comment by rejas** [comment]
@sdetweil could you take a look please?

**Comment by sdetweil** [comment]
see #3649

**Pull request merged**
