### PR TITLE
Fixtestcases  

### PR DESCRIPTION
**Pull request by sdetweil**
fix electron testcases to remove hard coded dates.. after #3599 fix

### CODE REVIEW

**Comment by khassel** [comment]
well, contains not only the testcases ... seems to be mixed up with #3587

**Comment by sdetweil** [comment]
yeh, don't know how that happened..

have local branch with fixes created from fixcaldates2, fixtestcases (as current branch)
switched to develop, pulled develop
switch to fixtestcases, merge develop
add testcases/commit/push

**Comment by sdetweil** [comment]
i can toss it and do again directly from develop

**Comment by sdetweil** [comment]
closing, redo

**Comment by sdetweil** [comment]
I hink it was

**Pull request closed without merging**
