### PR TITLE
Request only required information instead of all

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
Hopefully this solves the problem with arm64 (reported in PR #3337).

### CODE REVIEW

**Comment by khassel** [comment]
```bash
node@raspberrypi:/opt/magic_mirror$ npm start

> magicmirror@2.27.0-develop start
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[07.01.2024 22:36.05.347] [LOG]   Starting MagicMirror: v2.27.0-develop
[07.01.2024 22:36.05.375] [LOG]   Loading config ...
[07.01.2024 22:36.05.379] [DEBUG] config template file not exists, no envsubst
[07.01.2024 22:36.05.853] [ERROR] Whoops! There was an uncaught exception...
[07.01.2024 22:36.05.856] [ERROR] Error: write EFAULT
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at WriteStream._writeGeneric (node:net:931:11)
    at WriteStream._write (node:net:943:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at WriteStream.write (node:internal/streams/writable:337:10)
    at execSync (node:child_process:981:20)
    at node:electron/js2c/asar_bundle:2:12708
    at getFQDN (/opt/magic_mirror/node_modules/systeminformation/lib/osinfo.js:171:22)
    at /opt/magic_mirror/node_modules/systeminformation/lib/osinfo.js:219:15
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errno: -14,
  code: 'EFAULT',
  syscall: 'write'
}
[07.01.2024 22:36.05.858] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[07.01.2024 22:36.05.859] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MagicMirrorOrg/MagicMirror/issues
[07.01.2024 22:36.05.862] [LOG]   Loading module helpers ...
[07.01.2024 22:36.05.865] [LOG]   No helper found for module: alert.
[07.01.2024 22:36.05.884] [LOG]   Initializing new module helper ...
[07.01.2024 22:36.05.886] [LOG]   Module helper loaded: updatenotification
[07.01.2024 22:36.05.899] [LOG]   No helper found for module: clock.
[07.01.2024 22:36.06.106] [LOG]   Initializing new module helper ...
[07.01.2024 22:36.06.107] [LOG]   Module helper loaded: calendar
[07.01.2024 22:36.06.109] [LOG]   No helper found for module: compliments.
[07.01.2024 22:36.06.111] [LOG]   No helper found for module: weather.
[07.01.2024 22:36.06.314] [LOG]   Initializing new module helper ...
[07.01.2024 22:36.06.315] [LOG]   Module helper loaded: newsfeed
[07.01.2024 22:36.06.316] [LOG]   All module helpers loaded.
[07.01.2024 22:36.06.334] [LOG]   Starting server on port 8080 ...
[07.01.2024 22:36.06.340] [WARN]  You're using a full whitelist configuration to allow for all IPs
[07.01.2024 22:36.06.359] [LOG]   Server started ...
[07.01.2024 22:36.06.361] [LOG]   Connecting socket for: updatenotification
[07.01.2024 22:36.06.362] [LOG]   Starting module helper: updatenotification
[07.01.2024 22:36.06.363] [LOG]   Connecting socket for: calendar
[07.01.2024 22:36.06.365] [LOG]   Starting node helper for: calendar
[07.01.2024 22:36.06.366] [LOG]   Connecting socket for: newsfeed
[07.01.2024 22:36.06.367] [LOG]   Starting node helper for: newsfeed
[07.01.2024 22:36.06.368] [LOG]   Sockets connected & modules started ...
[07.01.2024 22:36.06.717] [ERROR] Whoops! There was an uncaught exception...
[07.01.2024 22:36.06.719] [ERROR] Error: write EFAULT
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at WriteStream._writeGeneric (node:net:931:11)
    at WriteStream._write (node:net:943:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at WriteStream.write (node:internal/streams/writable:337:10)
    at execSync (node:child_process:981:20)
    at node:electron/js2c/asar_bundle:2:12708
    at Object.getCodepage (/opt/magic_mirror/node_modules/systeminformation/lib/util.js:562:24)
    at /opt/magic_mirror/node_modules/systeminformation/lib/osinfo.js:256:34
    at ChildProcess.exithandler (node:child_process:438:5)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:514:28) {
  errno: -14,
  code: 'EFAULT',
  syscall: 'write'
}
[07.01.2024 22:36.06.722] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[07.01.2024 22:36.06.723] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MagicMirrorOrg/MagicMirror/issues
[07.01.2024 22:36.06.796] [ERROR] Whoops! There was an uncaught exception...
[07.01.2024 22:36.06.798] [ERROR] Error: write EFAULT
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at WriteStream._writeGeneric (node:net:931:11)
    at WriteStream._write (node:net:943:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at WriteStream.write (node:internal/streams/writable:337:10)
    at execSync (node:child_process:981:20)
    at node:electron/js2c/asar_bundle:2:12708
    at /opt/magic_mirror/node_modules/systeminformation/lib/system.js:64:21
    at ChildProcess.exithandler (node:child_process:422:7)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:323:12) {
  errno: -14,
  code: 'EFAULT',
  syscall: 'write'
}
[07.01.2024 22:36.06.799] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[07.01.2024 22:36.06.800] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MagicMirrorOrg/MagicMirror/issues
[07.01.2024 22:36.06.813] [LOG]   Launching application.
[07.01.2024 22:36.07.184] [INFO]  System information:
### SYSTEM:   manufacturer: ; model: Docker Container; raspberry: undefined; virtual: false
### OS:       platform: linux; distro: Debian GNU/Linux; release: 12; arch: arm64; kernel: 5.15.76-v8+
### VERSIONS: electron: 27.2.1; used node: 18.17.1; installed node: 21.5.0; npm: 10.2.4; pm2:
### OTHER:    timeZone: Europe/Berlin; ELECTRON_ENABLE_GPU: undefined
[07.01.2024 22:36.08.945] [LOG]   Create new calendarfetcher for url: https://ics.calendarlabs.com/76/mm3137/US_Holidays.ics - Interval: 604800000
[07.01.2024 22:36.09.111] [LOG]   Create new newsfetcher for url: https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
[07.01.2024 22:36.09.118] [INFO]  updatenotification: Updater Class Loaded!
[07.01.2024 22:36.09.120] [INFO]  updatenotification: Checking PM2 using...
[07.01.2024 22:36.09.122] [INFO]  Checking git for module: MagicMirror
[07.01.2024 22:36.09.160] [INFO]  updatenotification: You are not using pm2
[07.01.2024 22:36.09.886] [INFO]  Newsfeed-Fetcher: Broadcasting 25 items.
[07.01.2024 22:36.10.008] [INFO]  Calendar-Fetcher: Broadcasting 12 events from https://ics.calendarlabs.com/76/mm3137/US_Holidays.ics.
```

- node_modules/systeminformation/lib/osinfo.js:219:15
- node_modules/systeminformation/lib/util.js:562:24
- node_modules/systeminformation/lib/system.js:64:21

**Comment by KristjanESPERANTO** [comment]
I need to get my Rasperry Pi up and running again. Apparently testing on a Debian laptop is not enough....

**Comment by KristjanESPERANTO** [comment]
Except for manufacturer and raspberry, all the information is there. Can you remove them from the query?

**Comment by sdetweil** [comment]
I'll try to test on my odroid and Jetson nano

**Comment by khassel** [comment]
> Except for manufacturer and raspberry, all the information is there. Can you remove them from the query?

see https://github.com/MagicMirrorOrg/MagicMirror/pull/3337#issuecomment-1880188013

**Comment by sdetweil** [comment]
I got this on odroid (arm7)
```
### SYSTEM:   manufacturer: ; model: SAMSUNG EXYNOS (FLATTENED DEVICE TREE); raspberry: undefined; virtual: false
### OS:       platform: linux; distro: Ubuntu; release: 22.04.3 LTS; arch: arm; kernel: 6.1.61-16
### VERSIONS: electron: 27.2.0; used node: 18.17.1; installed node: 18.19.0; npm: 10.2.3; pm2: 
### OTHER:    timeZone: America/Chicago; ELECTRON_ENABLE_GPU: undefined
```

**Comment by sdetweil** [comment]
got this for /proc/cpuinfo
```
processor	: 0
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 84.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 3

processor	: 1
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 84.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 3

processor	: 2
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 84.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 3

processor	: 3
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 84.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 3

processor	: 4
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 120.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0xc0f
CPU revision	: 3

processor	: 5
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 120.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0xc0f
CPU revision	: 3

processor	: 6
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 120.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0xc0f
CPU revision	: 3

processor	: 7
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 120.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0xc0f
CPU revision	: 3

Hardware	: Samsung Exynos (Flattened Device Tree)
Revision	: 0000
Serial		: 0000000000000000
```

**Review by rejas — APPROVED** [review]

**Pull request merged**
