### PR TITLE
feat(compliments): add configuration for refreshing remote file on interval 

### PR DESCRIPTION
**Pull request by xsorifc28**
Hello and thank you for wanting to contribute to the MagicMirror² project

**Please make sure that you have followed these 4 rules before submitting your Pull Request:**

> 1. Base your pull requests against the `develop` branch.
> 2. Include these infos in the description:
>
> - Does the pull request solve a **related** issue?
> - If so, can you reference the issue like this `Fixes #<issue_number>`?
> - What does the pull request accomplish? Use a list if needed.
> - If it includes major visual changes please add screenshots.
>
> 3. Please run `npm run lint:prettier` before submitting so that
>    style issues are fixed.
> 4. Don't forget to add an entry about your changes to
>    the CHANGELOG.md file.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.

Thanks again and have a nice day!

### CODE REVIEW

**Comment by rejas** [comment]
Thanks for your PR.
Two things though:
- could you update the PR description and get rid of the default text?
- can you look into why the test are failing for the compliments now?

**Comment by sdetweil** [comment]
more than likely a syntax error

node -c  compliments.js 

will check language syntax

**Comment by sdetweil** [comment]
I just pushed PR 3630 which does all and with testcases

**Comment by xsorifc28** [comment]
> I just pushed PR 3630 which does all and with testcases, using your code plus more

Thank you much, apologies I have not been able to invest the time to ramp up on the project.

**Comment by xsorifc28** [comment]
Closing in favor of #3630

**Pull request closed without merging**
