### PR TITLE
Fix check for mastermerge label

### PR DESCRIPTION
**Pull request by rejas**
Mastermerge label wasnt checked correctly, this PR should hopefully fixes it for good

### CODE REVIEW

**Comment by khassel** [comment]
@rejas ready to merge?

**Comment by rejas** [comment]
Would like to wait until release is done

**Comment by rejas** [comment]
or we merge this and re-build the release?

**Comment by rejas** [comment]
@khassel updated it with some dep updates so I think we can merge it before we do the real 2.27.0 release

**Pull request merged**
