### PR TITLE
version 2.5 has been deprecated, changing default to 3.0

### PR DESCRIPTION
**Pull request by dkallen78**
I'm new to using GitHub as a collaborative platform so I'm very new to all of this, let me know if I goofed something and how I can do it better next time!

OpenWeather's One Call API has deprecated version 2.5 so it won't anymore. I changed the default value of apiVersion from 2.5 to 3.0 so newbies like me will have an easier time figuring it out!

### CODE REVIEW

**Comment by sdetweil** [comment]
I thought we also had to change the endpoint ?
and all PRs need a CHANGELOG.md update

**Comment by dkallen78** [comment]
I'm not sure about changing the endpoint. When I got hourly updates working on my MM, I only had to change the apiVersion property to "3.0" and it worked. My only change was to the default in the module code for the OpenWeather stuff. let me see if I can figure out how to do the changelog stuff...

**Comment by khassel** [comment]
> let me see if I can figure out how to do the changelog stuff...

well, you provided a new PR instead of committing and pushing the changelog stuff to the branch you used in this PR.

So please add the changelog stuff here or the other way: Add the changes done here to the new PR.

We need both in one PR for merging.

**Comment by dkallen78** [comment]
I don't know how to do that. But going forward, is this the workflow:
change code, update CHANGELOG; save both; commit both at the same time;
then do the pull request once both are queued up?

Sorry, I'm very new to this

**Comment by khassel** [comment]
workflow:
- change code, commit, push
- new changes (e.g. add changelog), add new commit and push
- create pull request
- if you want to change something after PR is created, just change code and create new commit and push (you must be on the same branch as before, you used branch `master` in this PR). The new changes will appear in the existing pull request

You have to do step 4 now.

Let me know if you want to try this yourself (otherwise I can do it).

**Comment by khassel** [comment]
I added the changes from here to https://github.com/MagicMirrorOrg/MagicMirror/pull/3496, so closing this.

**Pull request closed without merging**
