### PR TITLE
path resolve and sub/sub folder module

### PR DESCRIPTION
**Pull request by bugsounet**
Fix:
 - use `path.resolve` for `moduleFolder` and `defaultModuleFolder` path
 -  Fix module path in case of sub/sub folder is used (sample `module/test/test`)
 
---
case of module installation on `module/test/test`:

config will be:
```js
 {
    module: "test/test",
    ...
 }
```

module core will be:
```js
Module.register("test", {
...
```
`test.js` is used for module core (no change)

---

case of module installation on `module/test` (no change):
config will be:
```js
 {
    module: "test",
    ...
 }
```

module core will be:
```js
Module.register("test", {
...
```
so `test.js` is used for module core

---

In reality, with this patch, `module` config feature have 2 functionalites:
 -  determinate module path with more precision
 -  allow to use sub/sub folder in modules folder

### CODE REVIEW

**Comment by bugsounet** [comment]
Can you resetart test suite for `20.9.0\ and `20.x`
Thx

**Comment by sdetweil** [comment]
@bugsounet   you know YOU can restart 

if you click into the details of a test run  you can restart some/all the jobs (I know it was running) 
Screenshot at 2024-12-13 10-54-56

**Comment by bugsounet** [comment]
Not sure i have Access (i will verify next time)

**Review by khassel — APPROVED** [review]

**Comment by bugsounet** [comment]
@sdetweil : tested on a failed job -> no access, I can't restart it (#3659)

**Comment by khassel** [comment]
> no access, I can't restart it 

thats what I expected, Sam has more rights ...

**Pull request merged**
