### PR TITLE
Update compliments.js

### PR DESCRIPTION
**Pull request by devilsayshi**
Hello and thank you for wanting to contribute to the MagicMirror² project

**Please make sure that you have followed these 4 rules before submitting your Pull Request:**

> 1. Base your pull requests against the `develop` branch.
> 2. Include these infos in the description:
>
> - Does the pull request solve a **related** issue?
> - If so, can you reference the issue like this `Fixes #<issue_number>`?
> - What does the pull request accomplish? Use a list if needed.
> - If it includes major visual changes please add screenshots.
>
> 3. Please run `npm run lint:prettier` before submitting so that
>    style issues are fixed.
> 4. Don't forget to add an entry about your changes to
>    the CHANGELOG.md file.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.

Thanks again and have a nice day!

### CODE REVIEW

**Comment by rejas** [comment]
Hello and thanks for your PR. Please pay attention to the pre-filled text we provide for PRs. Can you be so kind and re-read it and adjust your PR accordingly?

**Comment by sdetweil** [comment]
and you can override the list of compliments used, by adding then to your MagicMirror config.js

so the words shown are all up to you, without changing any code

**Comment by KristjanESPERANTO** [comment]
I can't see the point of this PR. The default texts are okay and the changes are not an improvement in my opinion.

**Comment by sdetweil** [comment]
I agree, if the user  does t want to see the word 'sex' they can add their own compliments.  

wait for user reply, close by end of day June 10

**Comment by khassel** [comment]
> you can override the list of compliments used, by adding them to your MagicMirror config.js

> wait for user reply, close by end of day June 10

**Pull request closed without merging**
